### ISSUE TITLE
Does not work with 'watch'

### ISSUE THREAD

**Issue by drich10** [businesscritical/dishy#1]

**Comment by wendorf** [comment]
This is specifically a problem with imgcat, but we can maybe fix it anyway. `watch imgcat ~/Downloads/63.png` will recreate the issue.

**Comment by wendorf** [comment]
Turns out this is actually a problem with watch (at least some distributions of it), which strip non-printable characters. Would you be satisfied with a --watch flag e.g. `dishy beans --watch`?

**Comment by wendorf** [comment]
`watch dishy` is no good. As of this moment, dishy has learned the `--watch` flag.
