### ISSUE TITLE
avoid directly repeating images

### ISSUE THREAD

**Issue by ardnaxelarak** [businesscritical/dishy#10]
when using the --lots or --watch flag, it would be cool if before displaying an image it would compare it (the url or whatever) to the image it displayed before, and if it was the same one, pull a new image before displaying

**Comment by wendorf** [comment]
We only show repeat images when the image is really awesome. This request sounds like a regression.

![bad idea](http://i.giphy.com/3oEduHW0Y5OLTp8n1S.gif)

**Comment by ardnaxelarak** [comment]
@wendorf,

Thank you for your timely response.

However, the team that I represent who has decided to use your product has recently been victim of a slew of repeated images that were, sadly, not "really awesome" and were quite frankly, terrible.

If you could direct me to the part of your code where you perform a check to see if an image is "really awesome" or not, perhaps I can help diagnose your bug; but as it stands at present it appears that you are merely attempting to advertise a feature that does not exist.
We hope that you will address this issue, because while we love your product, this one particular bug is quite troublesome, and if it is not addressed we feel we might need to seek out a product that can better address our needs.

Thanks,
Kara

**Comment by wendorf** [comment]
https://github.com/businesscritical/dishy/blob/master/dishy
