### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by xoebus** [businesscritical/dishy#17]
![](http://www.mollieandfred.co.uk/images/the-bright-side-i-need-this-stuff-kids-wishlist-notebook-p3044-4043_zoom.jpg)

**Comment by utako** [comment]
Thanks for submitting your issue, @xoebus! We support Linux emotionally. It's doing a great job.

**Comment by utako** [comment]
![<3](http://img41.glitterfy.com/16054/glitterfy6142341T561B81.gif)
