### ISSUE TITLE
i would like to be able to copy the link address from the image

### ISSUE THREAD

**Issue by zrob** [businesscritical/dishy#2]

**Comment by wendorf** [comment]
Summarizing an in-person conversation @zrob and I had:

It's easier to add a flag like --wheres-that-from that outputs the URL of the last image dishy printed. e.g.:

```
dishy beans
dishy --wheres-that-from
```

I'm open to ideas for the flag name. Some possibilities:
- --wheres-that-from
- --whered-you-find-that
- --whaaaaaaaat
- --i-need-to-share-this
- --gimme
- --url
