### ISSUE TITLE
i want to see a lot of images

### ISSUE THREAD

**Issue by Gerg** [businesscritical/dishy#4]
what if instead of one image i could see a lot of them

that would be sweet

**Comment by utako** [comment]
Hi Greg,

Thank you for your issue. Would you mind specifying what "a lot" is in integer format?

Thank you,
@wendorf & @utako, dishy

**Comment by Gerg** [comment]
how about you type dishy potato --a-lot and you see a lot

**Comment by wendorf** [comment]
In the mean time, we have some we're not using that you can use for now.

![greg](http://i.giphy.com/1mht8tODXy0OA.gif)
![greg](http://i.giphy.com/qw9HmgeGN9yCY.gif)
![greg](http://i.giphy.com/8OKRWmYfDC2zu.gif)
![greg](http://i.giphy.com/zUSQoU8QgvlxC.gif)
![greg](http://i.giphy.com/wxI5834frV5GU.gif)
![greg](http://i.giphy.com/YTEsIw2zByRAk.gif)
![greg](http://i.giphy.com/ZVpc7pYM5n4MU.gif)
![greg](http://i.giphy.com/e3Ppuw9TDwf84.gif)
![greg](http://i.giphy.com/TlxjvIfz2ZNQc.gif)
![greg](http://i.giphy.com/lXiRnox22vuMUm1Og.gif)
![greg](http://i.giphy.com/3o7ZetAqTj9YiXYC9G.gif)

Let us know if this will work as a temporary workaround.
