### ISSUE TITLE
i want to see alot

### ISSUE THREAD

**Issue by Gerg** [businesscritical/dishy#6]
related to #4 

i want to be able to type dishy potato --alot and see a gif of alot 

![alot](http://thewritepractice.com/wp-content/uploads/2012/05/Alot-vs-a-lot1-600x450.png)

**Comment by wendorf** [comment]
Closed WONTFIX.

**Comment by wendorf** [comment]
NOTABUG

**Comment by utako** [comment]
gotcha

**Comment by wendorf** [comment]
![wontfix](http://img41.glitterfy.com/16043/glitterfy6141940T309B81.gif)

**Comment by Gerg** [comment]
![](https://media.giphy.com/media/S2kpGDgKvyc92/giphy.gif)

**Comment by wendorf** [comment]
Whoops, haven't closed this for a few days.

![closed](http://i.giphy.com/13mPeKqo7YBZhS.gif)

**Comment by wendorf** [comment]
Doing some dishy housekeeping. This issue should be closed.

![closed](http://i.giphy.com/TBuAgAgXXvPMY.gif)

**Comment by wendorf** [comment]
This is a pretty good issue.

**Comment by wendorf** [comment]
This issue should be closed.

**Comment by wendorf** [comment]
Closing.
