### ISSUE TITLE
Too many repeat gifs!

### ISSUE THREAD

**Issue by ghost** [businesscritical/dishy#8]
There HAS to be more corgi gifs than what dishy is giving me.... MORE PUPPY GIFS!

**Comment by wendorf** [comment]
How can I handle all these GIFs?!

![where are the corgis](http://i.giphy.com/J25GqHE9tPrwY.gif)

**Comment by ghost** [comment]
when life gives you lemons.... 
![image](https://cloud.githubusercontent.com/assets/16912416/13040319/b19fa586-d3e5-11e5-9192-4347bbcb66d0.png)
